### ISSUE TITLE
Update screenshot.png

### ISSUE THREAD

**Issue by richtabor** [godaddy-wordpress/go#145]
The current screenshot.png image needs updating to reflect the GoDaddy theme/brand. It should also be `1200x900` instead of the smaller size it currently is.   

**Current:**
<img width="580" alt="Screen Shot 2019-08-05 at 11 42 56 AM" src="https://user-images.githubusercontent.com/1813435/62477058-2ff32a80-b776-11e9-8402-047b44840beb.png">

**Comment by EvanHerman** [comment]
Screenshot has been updated for our submission to WordPress.org
https://github.com/godaddy-wordpress/go/blob/master/screenshot.png

If this is still valid and needs to be updated again, feel free to re-open 👌
