### ISSUE TITLE
Menu toggle background missing

### ISSUE THREAD

**Issue by jrtashjian** [godaddy-wordpress/go#190]
### Describe the bug:
The menu toggle is missing a background color on header variation 5 when the header has a background color. The navigation menu also doesn't have the correct background color when toggled.

### Screenshot (current):

![Screenshot from 2019-08-09 15-20-01](https://user-images.githubusercontent.com/375788/62803890-b29f2100-bab9-11e9-988c-7302452f7342.png)

![Screenshot from 2019-08-09 15-24-32](https://user-images.githubusercontent.com/375788/62804004-f72abc80-bab9-11e9-94c5-23481975afa0.png)

**Comment by richtabor** [comment]
Closing as we removed the 5th header variation (for the foreseeable future)
