### ISSUE TITLE
Improve WooCommerce alert messages

### ISSUE THREAD

**Issue by jrtashjian** [godaddy-wordpress/go#252]
### Describe the bug:
1. Alert message colors do not match the current design style and color scheme.
2. Icons within alert messages do not match the current design style and color scheme.
3. Links within alert messages do not match the current design style and color scheme.

### Screenshot (current):
![Screenshot from 2019-08-19 18-37-59](https://user-images.githubusercontent.com/375788/63304302-83a25f80-c2b0-11e9-9d23-e4c31082eb12.png)

![Screenshot from 2019-08-19 18-38-31](https://user-images.githubusercontent.com/375788/63304323-95840280-c2b0-11e9-8e23-6b957bb304ab.png)

![Screenshot from 2019-08-19 18-39-14](https://user-images.githubusercontent.com/375788/63304347-aa609600-c2b0-11e9-8e92-724188e265d8.png)

**Comment by richtabor** [comment]
We need to establish if this issue is still relevant.

**Comment by helgatheviking** [comment]
I believe those are default WooCommerce notice styles, so this doesn't seem like a bug so much as Go may wish to apply a little more of it's own style to them.

**Comment by jrtashjian** [comment]
I'm going to close this for now until we decide to do a styling pass across all of WooCommerce for Go.
