### ISSUE TITLE
Add to cart button displaying oddly with the Modern design style

### ISSUE THREAD

**Issue by richtabor** [godaddy-wordpress/go#384]
**Describe the bug:**
The Products "Add to Cart" button does not display well in the Modern design style, as we have a custom ::after which is interfering. 

**Screenshot(s):**
<img width="315" alt="Screen Shot 2019-10-15 at 10 23 58 AM" src="https://user-images.githubusercontent.com/1813435/66840368-f2f5a200-ef35-11e9-8bda-1ea03799fd35.png">

**Comment by EvanHerman** [comment]
I don't think this is valid any longer. I'm not seeing the same behavior on my end.
<img src="https://user-images.githubusercontent.com/5321364/67685145-ebd58780-f96a-11e9-9aa2-f9be387e1cc2.png" width="300" />
