### ISSUE TITLE
No styles on Fresh Install

### ISSUE THREAD

**Issue by ajmorris** [godaddy-wordpress/go#399]
**Describe the bug:**
I downloaded via the tagged version (v1.1.1) and installed on a fresh WP 5.2.4 with no plugins, except CoBlocks (as Go recommended). What it results in is that it appears that no CSS files seem to have content in them or something as there are no styles on the page. Not sure if this expected behavior or if I need to run something after the theme is installed.

**Link to the demo page where the issue exists:**
You can check it out here: https://go.ajmorrissites.com/
**Screenshot (current):**

https://d.pr/i/V16Ihf

**Screenshot (expected):**
No sure what is expected as the Styles aren’t loading.

**Comment by fjarrett** [comment]
Hey @ajmorris 👋Thanks for taking Go for a spin  🚗💨

Did you happen to download the development [source archive](https://github.com/godaddy-wordpress/go/archive/1.1.1.zip) (1.1MB) or the [release archive](https://github.com/godaddy-wordpress/go/releases/download/1.1.1/go.zip) (717KB)? I am able to reproduce the exact issue you describe here when attempting the source ZIP, but what you should install is the release build ZIP.

<img width="545" alt="skitch (11)" src="https://user-images.githubusercontent.com/522158/67446777-4e2f3080-f5d7-11e9-9dbc-2c3e23ac65a9.png">

**Comment by ajmorris** [comment]
@fjarrett Thanks Frankie! :) I knew it had to have been something on my end. Working from the iPad and was trying to be quick about getting it! Thanks for setting me straight.

**Comment by fjarrett** [comment]
@ajmorris Hey no problem, I'm glad it was a simple fix! Do let us know your likes and dislikes while trying out the theme. We'd love to hear your first reactions.

You may be interested in checking out this [Template Gallery](https://wpnux.godaddy.com/v2/) we built showcasing all that is possible with just 1 theme (Go) and 1 plugin (CoBlocks), or 2 plugins if you need an online store (WooCommerce).
