### ISSUE TITLE
Child theme for GoDaddy Go Theme

### ISSUE THREAD

**Issue by volodymyrpekh** [godaddy-wordpress/go#427]
Is there a child theme for GoDaddy Go Theme available?

**Comment by EvanHerman** [comment]
Hi @volodymyrpekh 

There is not currently a child theme available for Go but you can easily create one following the instructions at https://developer.wordpress.org/themes/advanced-topics/child-themes/#how-to-create-a-child-theme

Evan

**Comment by krogsgard** [comment]
Pretty lackluster response to a legit question. I was looking to see here as well, as I wanted to see what I need to do in terms of build processes, managing existing stylesheets, and other things that can be nuanced when working with more advanced themes.

[This thread here](https://github.com/godaddy-wordpress/go/issues/466) is significantly more helpful for others that see this issue.

**Comment by richtabor** [comment]
You're right @krogsgard. I'm working on proper documentation for extending the design styles in #490. Should help out. :)

**Comment by helveticadomes** [comment]
it would be great if GoDaddy offered a ready-made go child theme.

I have looked at the design styles, and they are good if only minor adjustments need to be made, or primarily colors are changed. 
But if you want to use the go theme primarily for the content area (Gutenberg blocks), and customize headers, footers, menus etc. and  then it's difficult to do it using the extended styles alone.

Another possibility would be if GoDaddy provides a partial template that only covers the content (content_area). I would have imagined it like this: 1 documentation that say what the pre-requirements are (for example what class/id is required for the content_area), 1 CSS with the variables, 1+ CSS with the styles for the content, maybe 1+ CSS for header/footer/menu
Of course i may be able to split current theme on my own, but i don't like to do that every time go theme has an update

PS: A huge compliment and thanks for this theme! There are not many themes that are as suitable for the Gutenberg editor as this one
