### ISSUE TITLE
Reduce vertical spacing on larger viewports

### ISSUE THREAD

**Issue by lukecarbis** [godaddy-wordpress/go#429]
**Describe the bug:**
There is far too much vertical spacing, especially on wider monitors (my monitor is 3360px wide). This seems to be due to the `--vertical-rhythm--lrg` css variable, which includes `vw` units. The problem is compounded when using headings and lists in posts.

**Link to the demo page where the issue exists:**
https://climbingtree.blog/rosh-hashanah-5780-2-day-menu/

**Screenshot (current):**
![Screen Shot 2019-12-31 at 3 56 23 pm](https://user-images.githubusercontent.com/1097667/71611669-945fcc00-2be6-11ea-9fc5-d42d49cb1482.jpg)

**Screenshot (expected):**
Something more like:
![Screen Shot 2019-12-31 at 4 00 24 pm](https://user-images.githubusercontent.com/1097667/71611679-ad687d00-2be6-11ea-889b-dabee3e10d48.jpg)

**Comment by nickhamze** [comment]
I'm having the same issue. Trying to convert sortabrilliant.com over to Go and the space between headings is just enormous.

**Comment by nickhamze** [comment]
@richtabor Any idea for a quick fix here? Something quick and dirty is fine. I just really want to start porting my sites over.

**Comment by richtabor** [comment]
@nickhamze The vertical rhythm is operated via these variables. Plugging this into the Additional CSS panel within the Customizer (with your own values) will manipulate the vertical spacing between. 

```
:root {
	--vertical-rhythm: 1.25rem;
	--vertical-rhythm--med: 2.25rem;
	--vertical-rhythm--lrg: calc(2rem + 10vw);
}
```

**Comment by nickhamze** [comment]
Thanks Rich.

**Comment by dbiscontin** [comment]
In WP > Appearance > Customise > Additional CSS, I pasted the following:

`:root {
	--vertical-rhythm: 1rem;
	--vertical-rhythm--med: 2rem;
	--vertical-rhythm--lrg: calc(1.5rem + 10vw);
}`

.. and hit Publish.

Admittedly, I do not understand --vertical-rhythm calculations (yet) but I was expecting a change in vertical layout, even if an undesirable one. Nothing happened. What am I missing?

**Comment by offero** [comment]
Nothing happened for me either.
