### ISSUE TITLE
Demos not loading

### ISSUE THREAD

**Issue by benfurfie** [godaddy-wordpress/go#441]
**Describe the bug:**
None of the demos are loading, either from the links in the readme, or the from the demo listings page (https://wpnux.godaddy.com/v2/).

It loads as a blank page, and no source code is rendered.

Issue confirmed as affecting both Firefox and Chrome, so unlikely to be browser issue.

**Expected behavior:**
The demos should load.

**Screenshot(s):**

![godaddy_theme_issue](https://user-images.githubusercontent.com/10786699/72609669-718b2280-391d-11ea-861b-c647cf22ad8b.gif)

**Priority** (select one):
- [ ] High - Functional blocker
- [x] Medium - Doesn't work as expected 
- [ ] Low - Not a big deal but we'd want to get to this eventually

**Comment by fjarrett** [comment]
@benfurfie Sorry about that, all fixed up now. Thanks for the report.
