### ISSUE TITLE
Go theme styles

### ISSUE THREAD

**Issue by nickhamze** [godaddy-wordpress/go#442]
Where do I find the theme styles? They look cool and I really want to try them out.

**Comment by fjarrett** [comment]
Hey @nickhamze, thanks for taking Go for a spin. You can find these style options under **Customizer > Site Design > Design Styles**.

**Comment by nickhamze** [comment]
I saw those but those names don't correspond to the theme styles you are promoting in your showcase and none of those create anything like you are showing in your showcase. I guess I'm just a bit confused.

**Comment by richtabor** [comment]
@nickhamze, are you referring to the content within those demos? Each of these design styles do correspond to each of the demos we've created. We don't however have importable block content associated with each demo. Perhaps that's the hang-up?

p.s. It's good seeing you around!

**Comment by fjarrett** [comment]
@nickhamze here is an example of what @richtabor is describing - all of our starter template examples can be previewed on-the-fly with a different style which demonstrates how easy it is to completely change the mood of your site without touching your content or swapping out themes.

https://wpnux.godaddy.com/v2/?debug=1&template=keynote&style=traditional (Default)
https://wpnux.godaddy.com/v2/?debug=1&template=keynote&style=modern
https://wpnux.godaddy.com/v2/?debug=1&template=keynote&style=trendy
https://wpnux.godaddy.com/v2/?debug=1&template=keynote&style=welcoming
https://wpnux.godaddy.com/v2/?debug=1&template=keynote&style=playful

**Comment by nickhamze** [comment]
Yeah, I kind assumed it would be like Squarespace where I could say hey I want to start with Alder and then it gives me a site that looks exactly like the demo that I can then edit. 

When I downloaded go I expected it to look like the demos but I got a vanilla WordPress theme.

**Comment by fjarrett** [comment]
@nickhamze That is exactly how it works from inside our Managed WordPress hosting plans. When spinning up a new site, customers can choose from any of these starter templates. We are still thinking through how to expose these to a wider audience outside our hosting platform.

<img width="1160" alt="Screenshot 2020-01-17 10 08 56" src="https://user-images.githubusercontent.com/522158/72627031-629e7300-3911-11ea-8111-b228509c4e30.png">

**Comment by richtabor** [comment]
> @nickhamze We are still thinking through how to expose these to a wider audience outside our hosting platform.
> 

Was going to say this exactly :)

**Comment by nickhamze** [comment]
Yeah I saw that, so that's what I was expecting. I honestly think that has to be the norm for all themes. WordPress is the only place where that doesn't happen. Spin up a Squarespace, Wix or Shopify site. The demo matches what you are given. I feel like I'm being catfished whenever I download a WordPress theme. 

I don't think it's enough anymore to just provide a color palette, design is made up of so much more than that. If you can figure out how to bring your managed experience to everyone they'll be parades in your honor.

**Comment by nickhamze** [comment]
I had kinda a crazy idea. What if you created a reusable block that contained a group that had all the blocks from one of your demo sites in them? That way a user could just insert that reusable block group on to a page, right click to turn it into a regular block and then have all the content they need to get started.

I know it's probably not an ideal interface but I think it would be a start.

**Comment by richtabor** [comment]
That's interesting. 🤔

Once patterns are in core we'll have all our common patterns/templates applied as well for everyone to access.
