### ISSUE TITLE
Consider adding .entry-content class

### ISSUE THREAD

**Issue by phpbits** [godaddy-wordpress/go#444]
**Describe the bug:**
`entry-content` class is missing. Is this intentional? Thanks!

**Comment by richtabor** [comment]
@phpbits Is the `entry-content` required? Have any insights on why you're looking for it? Thanks!

**Comment by phpbits** [comment]
@richtabor I think so because it's similar to `entry-title`. I'm using the class on plugins for content targeting as well. Most theme has this class to I assumed this is included on the theming standard.

**Comment by richtabor** [comment]
Added via https://github.com/godaddy-wordpress/go/pull/509
