### ISSUE TITLE
Exposing variables in the customizer 

### ISSUE THREAD

**Issue by nickhamze** [godaddy-wordpress/go#450]
Do you think you'd ever let people mess with the CSS variables in the customizer?

I ported [block.garden](https://block.garden) over to Go and I'm loving it. Between it and CoBlocks I was almost able to do everything I wanted. The only thing I need to do what change a few of the variables (increasing body font size and reducing vertical space) once Rich told me how. 

It would be really cool if you could change them in the customizer, maybe with a range slider. Especially things for sizes of fonts and such. By using the variables it's really easy to change why not give your users the ability to do it themselves.

**Comment by richtabor** [comment]
> Do you think you'd ever let people mess with the CSS variables in the customizer?

Maybe the Customizer, though probably within the editor instead (or both). I'd like to move away from the Customizer and have a defined design space within the editor to modify design variables.

> By using the variables it's really easy to change why not give your users the ability to do it themselves.

Exactly what we're thinking :)

**Comment by nickhamze** [comment]
Yeah I'm not a real fan of the customizer but I feel weird about editing things that effect the entire site on a particular post/page. But I think if you made a sidebar panel where it was super clear that all the settings there applied everywhere that would work ok.

**Comment by offero** [comment]
So how do we customize the font?
