### ISSUE TITLE
Took way to too trying to figure out how to change the header background color

### ISSUE THREAD

**Issue by nickhamze** [godaddy-wordpress/go#454]
**Describe the bug:**
I'm setting up a new Zune fansite and I'm using Go naturally. I went with the playful color scheme. I tried to change the header/footer background color and was baffled why it wasn't working. 

With the Frolic color scheme the header & footer backgrounds are #3f46ae and the primary color is also set to #3f46ae. I assumed that if I changed the primary color to something custom it would also change the background color, but it didn't.

In the code it said you had header/footer color controls and it finally dawned on me that those colors must be somewhere else in the customizer. I finally found them. 

I think you should have all the color controls on the site design page or at least automatically change the header/footer background color to match the custom primary color set on the playful scheme. It only really affect that color scheme as none of the others have backgrounds on the header/footer.

**Comment by richtabor** [comment]
Totally agree @nickhamze. Better surfacing style controls within the Customizer (perhaps via visual cues _on_ the header) is a good idea. I'm not 100% sold on putting all the color controls on the one Customizer panel, but perhaps there's some interesting logic we could employ to make that experience better. 🤔

I'm curious how this will work with block-based themes too. If coloring will simply be adding a background color to the columns/group block.

**Comment by nickhamze** [comment]
I don't know, when I hear "Site Design" I think color.  I would even go one step further and put all the colors together in one panel and combine the header & footer into one "Layout" panel. But it's up to you just wanted to point out the confusion I had. 

That an interested point about block based themes. I wonder what they'll do. You think there would have to be a way to set colors globally.

**Comment by mathetos** [comment]
I came here to say this exact thing. The color options are not useful unless they trigger the other color settings to be updated automatically. Additionally, have the global colors as the colorpicker presets would be really helpful as well in case I want to change the header background color to a different one of the global palette options

**Comment by mathetos** [comment]
Just updated locally and this looks excellent, very nice improvement. Thank you!
