### ISSUE TITLE
Creating custom design styles

### ISSUE THREAD

**Issue by fabiobarbosa** [godaddy-wordpress/go#466]
This is not properly a bug, but I would like to ask is there is any way I can extend the theme's own functions in my child theme, in order to add a custom design style (or maybe modify one of them).

Currently I'm overriding a bunch of the CSS variables and adding an @import with the font I need for my project and I'm aware that's quite an ugly and unsustainable hack.

Any hint?
Thanks in advance.

**Comment by richtabor** [comment]
Hey @fabiobarbosa, we're actually planning to add some relevant docs next week to surface design style creation/modification. In the meantime, I'm working on a [branch](https://github.com/godaddy-wordpress/go/tree/spacing) with a updating naming convention to the CSS variables, as well as a simplified design style system. There's still a bit to do, but you're welcome to give it a look over! :)

**Comment by colorful-tones** [comment]
@fabiobarbosa - I've begun creating a child theme based on Go. Here is the gist of it: https://gist.github.com/colorful-tones/f15044a6830af5d176f066617e1dbbf4

The hard part was copying over the build process: `.dev/*` and streamlining/customizing to a new design style, but not impossible. The heart of it is in the `functions.php` and `.dev/config/webpack.settings.js`, which I included in my Gist as well.

I'm sure @richtabor and GoDaddy team will have some great improvements on this though. Just wanted to share what I had. Thanks!
