### ISSUE TITLE
Add a changelog please

### ISSUE THREAD

**Issue by colorful-tones** [godaddy-wordpress/go#470]
Since WordPress.org theme directory does not really have a changelog, nor does this Github repo. It would be nice for freelancers, agencies, or any other people using Go to have a changelog available. Perhaps, just rolling something in to the Github Releases might be quickest win.

Some possible existing packages/tooling: 

* [`gren`](https://github.com/github-tools/github-release-notes)

**Comment by EvanHerman** [comment]
Hi @colorful-tones 

We do have a running changelog in the [readme.txt](https://github.com/godaddy-wordpress/go/blob/master/readme.txt#L110) file, as you may have seen. Similar to how we maintain [CoBlocks](https://github.com/godaddy-wordpress/coblocks) we could maintain a separate changelog.txt file and/or grab the changes from the readme.txt file and attach them to the [release notes](https://github.com/godaddy-wordpress/coblocks/releases).

I don't think that it would be a whole lot of work to get that implemented - possibly in the next release.

**Comment by colorful-tones** [comment]
> We do have a running changelog in the readme.txt file, as you may have seen.

@EvanHerman thanks for pointing out the `readme.txt`. I overlooked the obvious there! 

> Similar to how we maintain CoBlocks we could also maintain a separate changelog.txt file here and/or grab the changes from the readme.txt file and attach them to the release notes.

That would be super helpful. 🥇

**Comment by EvanHerman** [comment]
Great! I've got a PR up which updates a few things to include a new `changelog.txt` file as well as attach the latest release changes onto the release notes here on Github.
https://github.com/godaddy-wordpress/go/pull/475

We should be able to get that included in the next release. In the meantime, I will go back and retroactively add the release notes for each release.

Thanks for pointing this out!
