### ISSUE TITLE
Add GitHub to social media links

### ISSUE THREAD

**Issue by afragen** [godaddy-wordpress/go#472]
**Describe the bug:**
No link for GitHub profile on social menu.

**Expected behavior:**
Either have an entry for my GitHub profile or the ability to add any entry.

**Screenshot(s):**
none

**Priority** (select one):
- [ ] High - Functional blocker
- [ ] Medium - Doesn't work as expected 
- [x] Low - Not a big deal but we'd want to get to this eventually

**Comment by EvanHerman** [comment]
Hi @afragen 

We've included a filter to allow for custom social media icons/sites to be added. This can be done through the `go_avaliable_social_icons` [source](https://github.com/godaddy-wordpress/go/blob/2124978e733a8351f63cdeb00c4c95663dd91dcd/includes/core.php#L1092) filter inside of the `get_available_social_icons()` method.

You can easily add Github to the list of available social media sites by doing the following:

```php
/**
 * Add Github to the list of available social media icons
 *
 * @var array $social_networks Array of available social networks.
 *
 * @return array Filtered array of social media networks.
 */
add_filter( 'go_avaliable_social_icons', function( $social_networks ) {

	$social_networks['github'] = array(
		'label'       => 'Github',
		'icon'        => dirname( __FILE__ ) . '/github.svg',
		'placeholder' => 'https://github.com/Username',
	);

	return $social_networks;

} );
```

You'll want to create an MU plugin where you will add the above code. If you need assistance in creating the MU plugin we do have some documentation setup [here](https://godaddy.github.io/wp-primer-theme/tutorials-and-examples/tutorials/mu-plugin.html).

The code above also assumes that you have a `github.svg` icon alongside the MU plugin file. I've attached the icon that I used in my testing here for you to use if you choose.

If you need any help or have any questions, feel free to post back here and I'll help out as best I can.

Evan

**Comment by afragen** [comment]
Thanks Evan. I admit to not looking deeply for the docs. But I'm not certain I see a link to them in this repository.

**Comment by EvanHerman** [comment]
@afragen That documentation was setup for one of our other themes, Primer, so it's not specific to this Go theme. We are currently working on getting some better documentation up and improving what we do have for Go.

**Comment by EvanHerman** [comment]
@afragen 

Just a heads up, in the PR #508 we've got Github and YouTube landing in Go, so the code that you have may error. You can either remove that before you update to the next release (possibly 1.2.8) or you can future proof the code that I provided up above.

To future proof things so that they don't start throwing an error when the next release is out you can just check if Github exists in the social networks array before adding yours.

```php
/**
 * Add Github to the list of available social media icons
 *
 * @var array $social_networks Array of available social networks.
 *
 * @return array Filtered array of social media networks.
 */
add_filter( 'go_avaliable_social_icons', function( $social_networks ) {

	if ( ! array_key_exists( 'github', $social_networks ) ) {

		$social_networks['github'] = array(
			'label'       => 'Github',
			'icon'        => dirname( __FILE__ ) . '/github.svg',
			'placeholder' => 'https://github.com/Username',
		);

	}

	return $social_networks;

} );
```

That way Github is only added if it doesn't already exist.

Thanks again for the suggestion.

Best,
Evan

**Comment by afragen** [comment]
Thanks for the update Evan. Much appreciated.
