### ISSUE TITLE
Pricing $$ not resizing correctly in tablet mode

### ISSUE THREAD

**Issue by PTADenver** [godaddy-wordpress/go#474]
**Describe the bug: I'm using the pricing table with 3 columns.  When I preview the page in the design editor using table view, the dollar prices don't resize so that they flow outside of the pricing table.**

**Expected behavior: Either the pricing table column might stack, similarly to phone view, or the dollar amounts resize to fit within the column boundaries.**

**Screenshot(s):**
![Screen Shot 2020-03-03 at 8 10 34 PM](https://user-images.githubusercontent.com/61768732/75841696-9cc1b800-5d8b-11ea-8db8-a0ca14297ca8.png)

**Priority** (select one):
- [ ] High - Functional blocker
- [x] Medium - Doesn't work as expected 
- [ ] Low - Not a big deal but we'd want to get to this eventually

**Comment by EvanHerman** [comment]
Hi @PTADenver 

Does this occur outside of the Go theme? It sounds like this may be a bug with the CoBlocks pricing block and not directly related to the Go theme.

**Comment by PTADenver** [comment]
Hello!
I'm a newbie to Wordpress so I don't have that much experience or ability to be flexible ie.  a little scared to change the theme and then go back to the Go theme incase I break something.  But happy to concede that yes, what you're saying could be true.
Thks

**Comment by richtabor** [comment]
Yea Go doesn't handle the responsiveness of the tables. We _could_ potentially setup some styles to force the third column to display under the other two on tablet (within CoBlocks).

**Comment by richtabor** [comment]
I have a PR (https://github.com/godaddy-wordpress/coblocks/pull/1440) for CoBlocks which improves the mobile nature of three and four column Pricing tables (and four column layouts for other blocks, such as Services and Features.

**Comment by richtabor** [comment]
Closed via https://github.com/godaddy-wordpress/coblocks/pull/1440 💪
