### ISSUE TITLE
New CoBlocks form submit button does not inherit the design style colors

### ISSUE THREAD

**Issue by EvanHerman** [godaddy-wordpress/go#479]
**Describe the bug:**
With the refactor of the submit button becoming a innerblock component (https://github.com/godaddy-wordpress/coblocks/pull/1397), an unstyled form submit button does not inherit the design styles.

**Link to the demo page where the issue exists:**
N/A - this issue is related to an upcoming release of CoBlocks

**Screenshot (current):**
![image](https://user-images.githubusercontent.com/5321364/76362619-b0bf6980-62f7-11ea-8afc-158d8a60c384.png)

**Screenshot (expected):**
![image](https://user-images.githubusercontent.com/5321364/76362627-b6b54a80-62f7-11ea-82a9-9dda342fd3f9.png)

**Comment by richtabor** [comment]
@EvanHerman Does this still occur now that #1397 is merged?

**Comment by EvanHerman** [comment]
@richtabor No, this no longer occurs after #1397. Closing this out 👌
