### ISSUE TITLE
Cannot save copyright text in Customizer's Site Settings

### ISSUE THREAD

**Issue by macemmek** [godaddy-wordpress/go#494]
**Describe the bug:**

Hello! I cannot save the own copyright text in Customizer's Site Settings.
There's a notice about invalid value.

**PHP error log:**

> [01-Apr-2020 11:34:31 UTC] PHP Warning:  call_user_func_array() expects parameter 1 to be a valid callback, class 'Go\Customizer' not found in /.../app/public/wp-includes/class-wp-hook.php on line 287
> [01-Apr-2020 11:34:31 UTC] PHP Stack trace:
> [01-Apr-2020 11:34:31 UTC] PHP   1. {main}() /.../app/public/wp-admin/admin-ajax.php:0
> [01-Apr-2020 11:34:31 UTC] PHP   2. require_once() /.../app/public/wp-admin/admin-ajax.php:22
> [01-Apr-2020 11:34:31 UTC] PHP   3. require_once() /.../app/public/wp-load.php:37
> [01-Apr-2020 11:34:31 UTC] PHP   4. require_once() /.../app/public/wp-config.php:88
> [01-Apr-2020 11:34:31 UTC] PHP   5. do_action() /.../app/public/wp-settings.php:562
> [01-Apr-2020 11:34:31 UTC] PHP   6. WP_Hook->do_action() /.../app/public/wp-includes/plugin.php:478
> [01-Apr-2020 11:34:31 UTC] PHP   7. WP_Hook->apply_filters() /.../app/public/wp-includes/class-wp-hook.php:311
> [01-Apr-2020 11:34:31 UTC] PHP   8. WP_Customize_Manager->wp_loaded() /.../app/public/wp-includes/class-wp-hook.php:287
> [01-Apr-2020 11:34:31 UTC] PHP   9. WP_Customize_Setting->preview() /.../app/public/wp-includes/class-wp-customize-manager.php:932
> [01-Apr-2020 11:34:31 UTC] PHP  10. WP_Customize_Setting->post_value() /.../app/public/wp-includes/class-wp-customize-setting.php:339
> [01-Apr-2020 11:34:31 UTC] PHP  11. WP_Customize_Manager->post_value() /.../app/public/wp-includes/class-wp-customize-setting.php:553
> [01-Apr-2020 11:34:31 UTC] PHP  12. WP_Customize_Setting->sanitize() /.../app/public/wp-includes/class-wp-customize-manager.php:1824
> [01-Apr-2020 11:34:31 UTC] PHP  13. apply_filters() /.../app/public/wp-includes/class-wp-customize-setting.php:574
> [01-Apr-2020 11:34:31 UTC] PHP  14. WP_Hook->apply_filters() /.../app/public/wp-includes/plugin.php:206
> [01-Apr-2020 11:34:32 UTC] PHP Warning:  call_user_func_array() expects parameter 1 to be a valid callback, class 'Go\Customizer' not found in /.../app/public/wp-includes/class-wp-hook.php on line 287
> [01-Apr-2020 11:34:32 UTC] PHP Stack trace:
> [01-Apr-2020 11:34:32 UTC] PHP   1. {main}() /.../app/public/wp-admin/admin-ajax.php:0
> [01-Apr-2020 11:34:32 UTC] PHP   2. do_action() /.../app/public/wp-admin/admin-ajax.php:175
> [01-Apr-2020 11:34:32 UTC] PHP   3. WP_Hook->do_action() /.../app/public/wp-includes/plugin.php:478
> [01-Apr-2020 11:34:32 UTC] PHP   4. WP_Hook->apply_filters() /.../app/public/wp-includes/class-wp-hook.php:311
> [01-Apr-2020 11:34:32 UTC] PHP   5. WP_Customize_Manager->save() /.../app/public/wp-includes/class-wp-hook.php:287
> [01-Apr-2020 11:34:32 UTC] PHP   6. WP_Customize_Manager->save_changeset_post() /.../app/public/wp-includes/class-wp-customize-manager.php:2507
> [01-Apr-2020 11:34:32 UTC] PHP   7. WP_Customize_Manager->validate_setting_values() /.../app/public/wp-includes/class-wp-customize-manager.php:2760
> [01-Apr-2020 11:34:32 UTC] PHP   8. WP_Customize_Setting->sanitize() /.../app/public/wp-includes/class-wp-customize-manager.php:2352
> [01-Apr-2020 11:34:32 UTC] PHP   9. apply_filters() /.../app/public/wp-includes/class-wp-customize-setting.php:574
> [01-Apr-2020 11:34:32 UTC] PHP  10. WP_Hook->apply_filters() /.../app/public/wp-includes/plugin.php:206

**Priority** (select one):
- [ ] High - Functional blocker
- [x] Medium - Doesn't work as expected 
- [ ] Low - Not a big deal but we'd want to get to this eventually

**Comment by richtabor** [comment]
Reported here on WordPress.org: https://wordpress.org/support/topic/copyright-edit-error/

Verified.

**Comment by richtabor** [comment]
Closed via #497
