### ISSUE TITLE
Too much spacing in between blocks during preview or publishing, editor fine.

### ISSUE THREAD

**Issue by SygnusCentauri** [godaddy-wordpress/go#495]
**Describe the bug:**
I finished writing my first post under the new Gutenberg style blocks editor. I'm using the Godaddy built Go Theme with the Barista demo as my template. My article/post looks great in the editor, but when I preview or publish it, there are huge spaces in between some of the blocks. I checked it out in the code view in there is nothing in the code that would indicate space being made. 

For example, there is too much space between the title and the first paragraph, too much space between some paragraphs, too much space before and after an image, etc. Some blocks are fine and others aren't

As I said before, it all looks great in the editor and in the code view, so it must be something else affecting the margins. I really am baffled at this point. Any takers? 

Thank you.
**Link to the demo page where the issue exists:**
http://fulvicacidbenefits.com/is-fulvic-acid-isolate-effective-against-covid-19-coronavirus/
**Screenshot (current):**
editor view 1
![editor1](https://user-images.githubusercontent.com/63124272/78402760-7184ef80-75fb-11ea-8440-5f5fdb6ae4e5.jpg)
editor view 2
![editor2](https://user-images.githubusercontent.com/63124272/78402764-72b61c80-75fb-11ea-9855-94d6f4b50830.jpg)
preview view 1
![preview1](https://user-images.githubusercontent.com/63124272/78402766-72b61c80-75fb-11ea-8ca3-302ab8e6e171.jpg)
preview view 2
![preview2](https://user-images.githubusercontent.com/63124272/78402768-734eb300-75fb-11ea-8c4e-81077efb75ac.jpg)

**Screenshot (expected):**

**Comment by mathetos** [comment]
I was testing Go today locally and experienced the same issue. I noticed a conflict with babel-polyfil -- we use that in our GiveWP Stripe add-on, but we have a toggle to disable ours in these cases. That prevented that conflict (I'd recommend a similar toggle in Go if possible), but it didn't resolve the spacing issue. 

In one way or another, it seems the CSS vars are not rendering correctly on the frontend
![image](https://user-images.githubusercontent.com/930724/78457757-69f83180-7661-11ea-8bef-4fe0508c7a0e.png)

**Comment by mathetos** [comment]
Ya, looking through the rendered style-playful.css the only variables related to spacing are these:
![image](https://user-images.githubusercontent.com/930724/78458744-821f7f00-7668-11ea-9d11-3dd8edb2225f.png)

There is no `--go--spacing--vertical--lg` at all.

**Comment by mathetos** [comment]
Sorry... found it in `style-shared.css` 

But it's referencing `--go--viewport--basis` and I'm having a hard time finding that. 

![image](https://user-images.githubusercontent.com/930724/78458773-cca0fb80-7668-11ea-89b6-39fad5822232.png)

Just trying to provide info to make it easier to narrow down the source of the problem.

**Comment by SygnusCentauri** [comment]
Thanks for replying something. I still have not been able to resolve this issue. Please if anyone else can help, I'd greatly appreciate it, I like this theme and I don't want to have to change it because of this. If it's possible maybe to do some custom css code to fix this or adjust the top margins of blocks, or what have you, please let me know what code to use.

**Comment by richtabor** [comment]
We’re looking into this @SygnusCentauri - thanks for the report :)

**Comment by richtabor** [comment]
Hey team, the editor and frontend styling should be one-to-one now with the merge of #480 and today's release of Go 1.2.7. Mind giving it a look? Thanks!

**Comment by SygnusCentauri** [comment]
I just did the update and cleared cache on my site but it is still showing exactly as before. Can you please check it again and see if it still appears that way on your end? Thank you.

**Comment by mathetos** [comment]
Thanks @richtabor -- the editor styles definitely match the front-end results now much more accurately. It just feels like an obscene about of top-margin for a heading. Obviously it's easy to customize it via custom CSS, I'm just curious why that much heading top-margin is the default. If there's a style guide that informs that decision or something I'd love to see it out of curiosity. 

![image](https://user-images.githubusercontent.com/930724/79411514-d8899900-7f57-11ea-87f7-0e7bd3eef9cc.png)

**Comment by SygnusCentauri** [comment]
Yes that amount of space is what is bothering me this entire time and still no one has addressed it, which was the original issue. I'm not much of a coder myself, if no one is willing to change the default margins, can someone provide me with some custom css commands which I can input to at least change my own site to make it look normal?
