### ISSUE TITLE
Add youtube channel in the social media links in the theme

### ISSUE THREAD

**Issue by hussamasmar** [godaddy-wordpress/go#503]
**Describe the bug:**
The theme doesn't allow adding the footer youtube as part of the social medial platforms listed. It has facebook, instagram, twitter, linked in and pintrest only

**Link to the demo page where the issue exists:**

**Screenshot (current):**

**Screenshot (expected):**

**Comment by richtabor** [comment]
Good idea! We've closed via https://github.com/godaddy-wordpress/go/pull/508
