### ISSUE TITLE
Styles broken

### ISSUE THREAD

**Issue by FahadHussain** [godaddy-wordpress/go#536]
**Describe the bug:**
.min files missing in the dist folder and hence the site seems broken
**Expected behavior:**
.min files should be generated for all the _styles_ under dist/css
**Screenshot(s):**

**Priority** (select one):
- [ ] Medium - Doesn't work as expected

**Comment by FahadHussain** [comment]
For workaround:
look in **includes/core.php** for 
`$suffix = SCRIPT_DEBUG ? '' : '.min';`
and replace it with 
`$suffix = SCRIPT_DEBUG ? '' : '';`

**Comment by EvanHerman** [comment]
@FahadHussain 

We’ve gone ahead and released a new version of Go (1.3.1). This should fix the problems. So sorry about that, but thank you for reporting that here and giving us a chance to fix things.

Feel free to update to 1.3.1 and let us know if you are still having any issues.

Evan
