### ISSUE TITLE
Need links to social networks

### ISSUE THREAD

**Issue by anna-vanlee** [godaddy-wordpress/go#542]
Please add links to social networks:
https://vk.com/
https://ok.ru/

And Icons:
Telegram
Whatsapp
Viber
Facebook messenger

It is much easier to create a single block, insert the icons from the kit there, put links to my page, and attach this block automatically to each article
Icons are not in the "Share" message - it does not work, but in the sense of going to my page in the messenger and social networks and writing to me.

Advantages of the built-in icons: you do not need plug-in libraries and heaps of garbage in the system, it is simple and this is the absence of additional extensions on the site.

**Comment by EvanHerman** [comment]
Hi @anna-vanlee 

There are a number of social media platforms that are not included in the Go theme. The list would be exceptionally long if we attempted to include every possible social media network.

However, we have included a pretty easy way for users to add their own social media icons to the go theme via a custom plugin.

Take a look at the following comment on an issue from another user.
https://github.com/godaddy-wordpress/go/issues/472#issuecomment-594875207

The comment there provides some code to easily get custom icons added to the theme without much work.
