### ISSUE TITLE
Child theme and Demo Content Hello

### ISSUE THREAD

**Issue by anna-vanlee** [godaddy-wordpress/go#543]
I do not see them
(maybe I'm not looking there?)
And if without demo content you can - then the child theme is really needed !!!!

**Comment by helveticadomes** [comment]
Yes Child-theme would be great #427

**Comment by helgatheviking** [comment]
Would love to see a CoBlocks child theme since this appears to be it's successor. :)

**Comment by jonathanbardo** [comment]
I'm not sure I understand the question here. Anyone can do a child theme with Go and there is [documentation](https://github.com/godaddy-wordpress/go/blob/master/docs/design-styles/design-styles.md) on how to extend design style. We do not provide demo content as of right now.
