### ISSUE TITLE
Feature Request: Blog Archive and Single Post Options

### ISSUE THREAD

**Issue by seb86** [godaddy-wordpress/go#544]
I just started using this theme and it is great but I feel there are some basic options missing for those who still like control over the blog parts. After all WordPress was designed for blogging... initially.

So here are a few things that I would appreciate added to the theme customizer if it's not to much to ask for.

## Archive Page
* Show Excerpt or Full Content
* Show Featured Image

## Single Posts
* Featured Image Height
* Perhaps some image filters like on Instagram for the featured image
* Toggle Display of Author (Blogs posted by one author only generally don't need to link the author)
* Toggle Display of Post Meta (Don't see any currently)

**Comment by seb86** [comment]
Also maybe add the option to set the background position for featured image.

**Comment by richtabor** [comment]
You know, we thought about including some of these features, but with the pending inclusion of Full Site Editing and Template Parts, we've decided to experiment in that direction instead. We have some plans to start integrating Go into the FSE framework shortly, now that it's becoming much more solid.

**Comment by seb86** [comment]
Is there a time frame for Full Site Editing @richtabor ?
