### ISSUE TITLE
[High] Adding Google Analytics tracking tag

### ISSUE THREAD

**Issue by bigfito** [godaddy-wordpress/go#546]
**Describe the bug:**

Hi there,

I am having a headache trying to find the way how to add the following code in the HEAD section of all of my pages:

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-">
</script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-');
</script>

¿How can I achieve that guys?

**Expected behavior:**

**Screenshot(s):**

**Priority** (select one):
- [ ] High - Functional blocker

**Comment by bigfito** [comment]
Hey, @richtabor, @christopherkurth, @EvanHerman

Any of you could help me on this? I don't want to think I paid GoDaddy for your terrible support.

Thanks.

**Comment by richtabor** [comment]
Hey @bigfito, this isn't an issue relative to the theme - but I'll gladly point you in the right direction. If you're not familiar with PHP, you may certainly use the [Header and Footer Scripts](https://wordpress.org/plugins/header-and-footer-scripts/) plugin to add that script to all your pages. The [plugin's documentation](https://www.digitalliberation.org/docs/header-and-footer-scripts/?utm_source=wporg&utm_medium=wppluginpage&utm_campaign=wp_hfs) walks you through it pretty well.
