### ISSUE TITLE
Add a selector to show/hide categories from displaying

### ISSUE THREAD

**Issue by gdandrija** [godaddy-wordpress/go#551]
Describe the bug: other than changing the theme's code there is no way the user can toggle a category display using the customizer. This is more a feature request rather than an issue, but it would be nice if users could choose if they want categories to display or not.

Link to the demo page where the issue exists: https://wp-themes.com/go/?p=36

Screenshot (current): https://i.imgur.com/LBVaOrX.png

Screenshot (expected): https://i.imgur.com/zctIHhi.png

**Comment by jrtashjian** [comment]
Closing this issue as it will be addressed in the [Full Site Editing](https://github.com/godaddy-wordpress/go/pull/855) work currently underway in Go.
