### ISSUE TITLE
Menu doesn't close when clicking on the menu item that has ID as href

### ISSUE THREAD

**Issue by PavleMarjanovic** [godaddy-wordpress/go#557]
When setting the ID as href in the menu and clicking on that link, it doesn't close the menu div on the mobile view.

It should scroll to the appropriate section ID and close the menu.

**Priority** (select one):
- [ ] High - Functional blocker
- [ ] Medium - Doesn't work as expected 
- [X] Low - Not a big deal but we'd want to get to this eventually

**Comment by mmits-chm** [comment]
Would be glad to have this fixed soon as mobile menu won't work for a one page design as it should.

 **Priority** (select one):
* [x]  High - Functional blocker
* [ ]  Medium - Doesn't work as expected
* [ ]  Low - Not a big deal but we'd want to get to this eventually

**Comment by wakanaattori** [comment]
This is really, really, really critical problem. Such a large proportion of usage is mobile usage.

**Comment by Magnus176** [comment]
Really critical problem! Please fix asap.

**Comment by wakanaattori** [comment]
A workaround is to use the full address in menu instead of the anchor, for example: 

https://www.example.com/#anchor 

instead of 

#anchor

**Comment by mmits-chm** [comment]
The workaround with the full adress **doesn't work** either. Tested it on several sites, no success.

**Comment by wakanaattori** [comment]
Sorry to hear that :/ On my page that workaround does its job. Is your site public? When I had Maintenance Mode -plugin active workaround didn't work either, but now it is working when the site is public.

**Comment by Magnus176** [comment]
Unfortunately The workaround with full address doesn't work for me either.
