### ISSUE TITLE
The primary menu item that has subitems doesn't act like a link

### ISSUE THREAD

**Issue by PavleMarjanovic** [godaddy-wordpress/go#573]
**Describe the bug:**
The menu item that has subitems doesn't act like a link.

**Expected behavior:**
The menu item that has subitems that have defined link should act as the link.

**Screenshot(s):**
http://prntscr.com/u5qmlb

**Priority** (select one):
- [x] High - Functional blocker
- [ ] Medium - Doesn't work as expected 
- [ ] Low - Not a big deal but we'd want to get to this eventually

**Comment by richtabor** [comment]
Originally reported in #529. We're on it - thanks for the report @PavleMarjanovic. 💪
