### ISSUE TITLE
Feature Request: Sidebars

### ISSUE THREAD

**Issue by hendronf** [godaddy-wordpress/go#578]
Maybe I've missed it, but I'd love to have the ability to use a sidebar (on the left or right side). 

Primary use case for me would be menu for logged in users to manage certain services, and on a "listing" page so I can seperate the layout a little (I could achieve this second one with a Gutenberg column).

This is the site I'm working on www.speakeasy.nz - a directory for counsellors and therapists.

**Comment by richtabor** [comment]
Hey Fearghal, cool idea (and super fun name for the site). We don't have plans to hedge a full sidebar template in Go, but you can try leveraging the Columns block (which now has resizable columns) to achieve a 70/30 split for a sidebar.
