### ISSUE TITLE
Font and spacing not loading in Gutenberg

### ISSUE THREAD

**Issue by Palingenae** [godaddy-wordpress/go#589]
**Describe the bug:** 
Using [Design Style Extension](https://github.com/godaddy-wordpress/go/blob/master/docs/design-styles/design-styles.md) and Gutenberg with CoBlocks, stylesheet's Typefaces and Spacing are not working while making a new page. Maybe it is not loaded or just not working. And documentation is not covering that.

**Expected behavior:**
Stylesheet is used to make pages with Gutenberg and have WYSIWYG entirely working while bringing Style Extension to the theme.

A more detailed documentation to explain how to use files to make Design Styles Extension work correctly.

**Screenshot(s):**
![Integrated Go + Wordpress theme edition : Front-End](https://user-images.githubusercontent.com/6728594/94584064-75c65880-027e-11eb-9abf-70eca4bdb4bb.png)
![Integrated Go + Wordpress theme edition : Editing a new page](https://user-images.githubusercontent.com/6728594/94584069-76f78580-027e-11eb-9d3c-10cc3ed1ae8c.png)

**Priority** (select one):
- [ ] High - Functional blocker
- [x] Medium - Doesn't work as expected 
- [ ] Low - Not a big deal but we'd want to get to this eventually

**Comment by richtabor** [comment]
Hey @Palingenae Could you post a link to the style extension you are using? I'd like to test it first-hand if possible.

**Comment by Palingenae** [comment]
You want me to upload it?

**Comment by richtabor** [comment]
Could you make a [gist](https://gist.github.com) perhaps?

**Comment by EvanHerman** [comment]
I am going to close this issue out. If this is still an issue that you are facing, please comment back here and we can open it back up and try and figure out what is happening and come up with a solution.
