### ISSUE TITLE
Add Elementor Font Support

### ISSUE THREAD

**Issue by leonfilser** [godaddy-wordpress/go#590]
**I tried to use Elementor to style some text on my local website**
When changing the fontsize in Elementor the displayed fontsize didn't change.
I found out that the themes CSS is overriding Elementors CSS

**Priority** (select one):
- [ ] High - Functional blocker
- [x] Medium - Doesn't work as expected 
- [ ] Low - Not a big deal but we'd want to get to this eventually

Fortunately i could solve the issue by adding the following to the style.css of my child theme:

    .elementor-text-editor p, .elementor-text-editor h1, .elementor-text-editor h2, .elementor-text-editor h3, .elementor-text-editor h4, .elementor-text-editor h5, .elementor-text-editor h6 {
    	font-size: inherit;
    }

**Comment by jrtashjian** [comment]
Closing this issue as we focus on the [Full Site Editing](https://github.com/godaddy-wordpress/go/pull/855) work currently underway in Go.
