### ISSUE TITLE
Primary Menu: Dropdown disappears after moving the cursor down

### ISSUE THREAD

**Issue by jonasschoen** [godaddy-wordpress/go#610]
Hi developers, 

thank you for your work on this theme. I like it a lot. It seems though that with the latest update a bug appeared. Other people described it as well in the [WordPress forum](https://wordpress.org/support/topic/cannot-navigate-dropdown-menu-items-after-theme-update/).

If the option is activated, that the sub-categories in the primary menu should expand on hover, they disappear again if you move the cursor down to click a sub-item. I can reproduce it on my website [https://franzoesische-friedrichstadtkirche.de/](https://franzoesische-friedrichstadtkirche.de) (although I might downgrade now to solve it for now.

It would be great if you had a look into it.

Cheers,
Jonas

**Comment by richtabor** [comment]
Hey @jonasschoen, just writing to let you know that we've resolved this issue on [Nov 12](https://wordpress.org/support/topic/cannot-navigate-dropdown-menu-items-after-theme-update/#post-13655901). Thanks for reporting it and let us know if you run into anything else. 👋
