### ISSUE TITLE
Checkboxes show as solid boxes

### ISSUE THREAD

**Issue by cherrador** [godaddy-wordpress/go#613]
**Describe the bug:**
Our GoDaddy site upgraded the Go theme from 1.3.6 to 1.3.8. Then the checkboxes show as black solid boxes, without any cue when they are clicked and toggle. 

I have traced the error due to changes one the file master/.dev/assets/shared/css/config/mixins.scss
```scss
@mixin checkbox-label-before {
	//mask-image: url(../images/checkbox.svg);
}

@mixin checkbox-label-checked-before {
	//mask-image: url(../images/checkbox-checked.svg);
}
```
The required masks images are commented out but the is no coded default alternative. Why this was done? There is no clear explanation of the change other than refactoring for SCSS implementation.

I have to revert my site back to the previous 1.3.6. The 1.3.7 version has also the same problem.

**Expected behaviour:**
Checkboxes should be outlined boxes and when they are selected they should show a checkmark or fillup boxes.

**Screenshot(s):**
![good](https://user-images.githubusercontent.com/12229855/99029464-838b2100-2540-11eb-8b24-513d37ab472a.PNG)
This the 1.3.6 (good), first checkbox is selected
![bad](https://user-images.githubusercontent.com/12229855/99029503-9f8ec280-2540-11eb-8b32-c1c508254d31.PNG)
This is 1.3.8 (bad), first checkbox is selected (???)

**Priority** (select one):
- [x] High - Functional blocker
- [ ] Medium - Doesn't work as expected 
- [ ] Low - Not a big deal but we'd want to get to this eventually

**Comment by richtabor** [comment]
I confirmed this issue occurs within the CoBlocks Form block. Before turning on the `mask-image` we need to confirm the WooCommerce checkboxes remain fine https://github.com/godaddy-wordpress/go/pull/598.

**Comment by cherrador** [comment]
@richtabor Thanks for taking a look into it. If I get it right, this issue was caused to fix other problem on WooCommerce and you are in the process of testing a WooCommerce alternative before re-enabling the SVG for the checkboxes.
