### ISSUE TITLE
Assumptions about text color within any block that "has-tertiary-background-color" mean manual color palette selection is ignored

### ISSUE THREAD

**Issue by SoYoureAWaffleMan** [godaddy-wordpress/go#627]
Style rules written into GO css prevent the user from choosing what color text goes e.g. on a `button` or inside a `cover` block. 

I would expect a button with the class "has-tertiary-background-color" to inherit the tertiary background color with no change in text color, but when I set the BG to "tertiary" the following rule is applied as well:

```
:root .has-tertiary-background-color, :root .has-tertiary-background-color a:not(.wp-block-button__link) {
    color: var(--go-heading--color--text);
}
```
I don't understand why the heading color is applied so liberally, shouldn't it only apply to headings? And why add the second selector when the first one has already changed the color of the button -> anchor element?

Same with text in cover blocks where this rule overrides a color chosen from the palette :

```
.wp-block-cover.has-tertiary-background-color p {
    color: var(--go--color--primary);
}
```

Same thing - I don't understand why this is desired behaviour, and it surely shouldn't prevent changing text color via the palette.

As I don't understand the intended behaviour I can only suggest these rules are removed. Please correct me if I'm missing something.

Demo here https://movema.cloudaccess.host/test-page-for-go-tertiary-issues

Apologies for the nasty green-on-red!

Screenshot: editor (good)

![Screenshot from 2020-12-27 18-48-21](https://user-images.githubusercontent.com/6367213/103177677-6a320000-4874-11eb-80ac-f1a4f36d45ec.png)

Screenshot: outcome (confusing)

![Screenshot from 2020-12-27 18-51-01](https://user-images.githubusercontent.com/6367213/103177688-83d34780-4874-11eb-8dd7-da7b2d739f08.png)

**Comment by richtabor** [comment]
@SoYoureAWaffleMan Thanks for the detailed report, I'm looking into it. 

The main reason I have set the tertiary color to apply a heading text color, is that the core style application is `white`, regardless of the background color applied. There does need to be better checks for when colors are applied to text within the blocks.

**Comment by jrtashjian** [comment]
Closing this issue as it will be addressed in the [Full Site Editing](https://github.com/godaddy-wordpress/go/pull/855) work currently underway in Go.
