### ISSUE TITLE
Can't delete header logo image

### ISSUE THREAD

**Issue by pschellhase** [godaddy-wordpress/go#640]
I am setting up a personal website using the Go theme. 

I am trying to eliminate the "logo" image in the header and instead use the default site title and description.

Whenever I delete the image and apply changes, on the next page refresh the logo image is still there and the site title / description are invisible.

Tried deleting cache on WP and locally but it doesn't seem to help.

**Priority** (select one):
- [x] High - Functional blocker
- [ ] Medium - Doesn't work as expected 
- [ ] Low - Not a big deal but we'd want to get to this eventually

**Comment by AnthonyLedesma** [comment]
Hi @pschellhase, I am unable to replicate the inability to delete the site logo. Here is what I am seeing on my end.

![siteLogoDeleting](https://user-images.githubusercontent.com/30462574/112889248-3db39d00-908a-11eb-85a2-fbd1e12dade2.gif)

![siteTitleDeletion](https://user-images.githubusercontent.com/30462574/112889495-8ec39100-908a-11eb-9651-70c5863c3007.gif)

**Comment by AnthonyLedesma** [comment]
Closed until we can replicate the issue or gain more understanding.
