### ISSUE TITLE
When using a credit card gateway at checkout additional radio buttons are being added

### ISSUE THREAD

**Issue by simonporter007** [godaddy-wordpress/go#646]
**Describe the bug:**
If the merchant is using a credit card gateway at checkout, additional radio buttons are being added before each input field. This was tested on both "trendy" and "modern" theme styles.

**Expected behavior:**
Only the payment methods should have a radio button selector, to toggle between the different payment options.

**Screenshot(s):**
https://cloud.skyver.ge/OAug2dw6
https://cloud.skyver.ge/p9u8L4E4

**Priority** (select one):
- [ ] High - Functional blocker
- [x] Medium - Doesn't work as expected 
- [ ] Low - Not a big deal but we'd want to get to this eventually

**Comment by EvanHerman** [comment]
Thanks @simonporter007 

This should now be resolved. This was closed by https://github.com/godaddy-wordpress/go/pull/647
