### ISSUE TITLE
Mismatch of has-{}-padding value in Go and CoBlocks 

### ISSUE THREAD

**Issue by petskratt** [godaddy-wordpress/go#659]
**Describe the bug:**

Styles for `has-{}-padding` classes are loaded in different order in editor and on page when using Go + CoBlocks, resulting in visual mismatch (editor has Go padding, live view CoBlocks padding). Issue noticed with Hero block.

Add Hero block to page, set in block options padding to Huge
Large padding (> 100px) is visible in editor
Publish page, observe - padding is ca 30px

In use: WP 5.7, Go 1.4.3, CoBlocks 2.10.0

**Link to the demo page where the issue exists:**

Issue can be seen on https://wpnux.godaddy.com/v2/?template=keynote - "Hi, I'm Mark..." has class .has-huge-padding, shown with minimal padding and looking different from sample screenshot.

**Screenshot (current):**

Current live preview of Keynote theme, small padding in use:

![image](https://user-images.githubusercontent.com/712310/114681408-cc751a80-9d16-11eb-9ef8-7187d3d49a56.png)

**Screenshot (expected):**

After disabling `.content-area__wrapper .has-huge-padding [...] {padding: var(--coblocks-spacing--4, 2em);}` in inspector:

![image](https://user-images.githubusercontent.com/712310/114681438-d26afb80-9d16-11eb-911f-0d7d4a9a1f9a.png)

**Comment by jrtashjian** [comment]
This looks more like a CoBlocks bug. Closing as we will be migrating away from the CoBlocks Hero block in the future.
