### ISSUE TITLE
Option to prevent title and tagline from being displayed

### ISSUE THREAD

**Issue by srbrtz** [godaddy-wordpress/go#664]
**Describe the bug:**
We have the name of our organization embedded in our logo. Therefore it is redundant to display the title in the header. It really does not look good right now because our logo is quite big and the spacing is very tight.

Deleting the title and tagline leaves the website nameless, so that is not really an option.

**Expected behavior:**
Option in the customizer to disable title and tagline from being displayed. We temporarily removed the logo from our website for now but it would be great to have an option to fix this!

**Screenshot(s):**
<img width="959" alt="Bildschirmfoto 2021-05-05 um 19 30 59" src="https://user-images.githubusercontent.com/83722903/117183995-845a8c80-add8-11eb-9b70-acd6521d8c79.png">

**Priority** (select one):
- [x] High - Functional blocker
- [ ] Medium - Doesn't work as expected 
- [ ] Low - Not a big deal but we'd want to get to this eventually

**Comment by rcdINC** [comment]
Hello: I have the same issue with one of my client websites that uses the Go theme. I agree with @srbrtz, there needs to be a setting in the site identity settings that allow you to hide the site title and tagline.

**Comment by znlr** [comment]
I have the same issue. I agree with @srbrtz. I can not hide the site title from the pages. Actually, I do not even see the option to hide the site title. Please fix it.

**Comment by FelicianoBV** [comment]
You can, with this CSS:

```
.site-description.sm\:display-block
, .site-title {
	display: none;
}
```
