### ISSUE TITLE
ISBAT change text colors consistently on the Hero block

### ISSUE THREAD

**Issue by ehamwey** [godaddy-wordpress/go#677]
### Describe the bug:
When the background color is set to Primary on the Hero block, the Text color controls no longer work. Additionally, the text color controls do not affect the Hero header unless it is the selected text element. Using a theme other than Go does not present this behavior. This is related to the CoBlocks color selector. Originally reported in godaddy-wordpress/coblocks#1902.

### To reproduce:
1. Add a Hero block
2. Select the overall block
3. Set the background color to Primary
4. Try to change the text color (no effect)
5. Set the background color to something other than Primary, or clear it
6. Try to change the text color (caption color changes)

### Expected behavior:
Caption and heading colors should change regardless of background colors

### Screenshots:
![Untitled](https://user-images.githubusercontent.com/9936886/120696805-fdeaa680-c47a-11eb-8007-7bb24deb6618.gif)

### WordPress version:
5.7.2

**Comment by jrtashjian** [comment]
This looks more like a CoBlocks bug. Closing as we will be migrating away from the CoBlocks Hero block in the future.
