### ISSUE TITLE
User request - Have option to display featured image for each post on blog page

### ISSUE THREAD

**Issue by gdaleks** [godaddy-wordpress/go#683]
https://wordpress.org/support/topic/missing-featured-images-from-blog-page/

The user inquired whether it would be possible to display the featured image of the post as a thumbnail in the post list on the blog page.

**Comment by jrtashjian** [comment]
Closing this issue as it will be addressed in the [Full Site Editing](https://github.com/godaddy-wordpress/go/pull/855) work currently underway in Go.
