### ISSUE TITLE
Mobile Friendly Navigation

### ISSUE THREAD

**Issue by stantond** [godaddy-wordpress/go#686]
Thanks for the great theme! I've hit a problem with my users navigating on mobile.

I'm using header layout option three, and have found users of my site are struggling to work out how to access my pages when on mobile, to the point where I've had to replicate the primary navigation into the footer so that they can be found.

The ... icon is a common standard for "More", which makes no sense in this context. If an icon is to trigger a hamburger menu, using the hamburger menu icon would take advantage of the mental model our users already have when looking for a menu on mobile sites and apps.

Alongside mobile app convention, a menu button is typically on the left (the side the menu tray appears from), while the search button is on the right. This header option currently has these the wrong way around.

**Comment by jrtashjian** [comment]
Closing this issue as it will be addressed in the [Full Site Editing](https://github.com/godaddy-wordpress/go/pull/855) work currently underway in Go.
