### ISSUE TITLE
Widget area and Block functionality

### ISSUE THREAD

**Issue by icditadmin** [godaddy-wordpress/go#734]
Is there a way to enable the WP Widget area on the side of a page with the Go theme?  (along with using Blocks to add items to the widget area)

When using the Go theme, I cannot find the Widget section in the Appearance section.

Mike

**Comment by tnchuntic** [comment]
Big UP for this one... experiencing also this issue where I couldn't find any widget area/panel and double-checked the code and couldn't find any "register_sidebar" called in Go Theme.

**Comment by gdandrija** [comment]
Upvoting this one, a similar request reported on WordPress.org: https://wordpress.org/support/topic/can-i-add-a-block-or-a-widget-to-the-go-theme/

**Comment by icditadmin** [comment]
Does anyone know of an alternative to the Go theme, one that does have this widget area block functionality? I believe we're going to be moving to something else, as we can't really delay any longer.

**Comment by jrtashjian** [comment]
Closing this issue as we focus on the [Full Site Editing](https://github.com/godaddy-wordpress/go/pull/855) work currently underway in Go.
