### ISSUE TITLE
Add cart button in the header

### ISSUE THREAD

**Issue by uev1** [godaddy-wordpress/go#735]
I suggest to add an option in customization to show or not a "bag" icon next to search icon that links to Woocommerce cart.
A set of icons can be very useful, this includes a user area, cart or any other custom button in the same area as search button

**Comment by EvanHerman** [comment]
Hi @uev1

We do have a cart icon show up in the header, next to the search icon, when WooCommerce is installed. It will only show up when you have at least one item in the cart. If the cart is empty the icon will not show up.

<img width="488" alt="image" src="https://user-images.githubusercontent.com/5321364/159705317-8441fd91-6397-4959-91f5-8b4e05430eb1.png">

As for other, custom, icons - you can use the built in actions to add any icons you want. Take a look at https://github.com/godaddy-wordpress/go/blob/master/includes/woocommerce.php for an example of how we are showing the icon up in the header.

**Comment by npadhikari** [comment]
@EvanHerman  Hi, I need cart icon to be displayed all the time, even if it is empty. Any tips on how to achieve it. Thank you for the awesome theme.
