### ISSUE TITLE
Add TikTok option to social links

### ISSUE THREAD

**Issue by amenk** [godaddy-wordpress/go#738]
**Describe the feature:**

When editing /wp-admin/customize.php -> Social, there is no TikTok option

**Expected behavior:**

Tiktok links can be added

**Priority** (select one):
- [ ] High - Functional blocker
- [x] Medium - Doesn't work as expected 
- [ ] Low - Not a big deal but we'd want to get to this eventually

**Screenshot**
![ksnip_tmp_eeZKda](https://user-images.githubusercontent.com/1087128/147418571-7ff82666-cbd9-49c5-a5f7-4ae325b3750d.png)

**Comment by amenk** [comment]
The Logo is to be attributed CC-BY to FontAwesome. Do we have to add this to the license file?

**Comment by EvanHerman** [comment]
I'm going to close out this issue since the feature has been merged and should be released to WordPress.org at this point. Thanks again for this suggestion 👍
