### ISSUE TITLE
Footer-4.php : Add functionality for text or images in the footer section

### ISSUE THREAD

**Issue by samdavyd** [godaddy-wordpress/go#740]
**Describe the bug:**
Can't add text or images under the site title in the foot-4 option that has menu links, copyright date, and social icons
**Expected behavior:**

**Screenshot(s):**
![image](https://user-images.githubusercontent.com/56747904/147992349-aaf4a713-11dc-4b14-89f1-601dc1818f53.png)

**Priority** (select one):
- [ ] High - Functional blocker
- [X] Medium - Doesn't work as expected 
- [ ] Low - Not a big deal but we'd want to get to this eventually

**Comment by jrtashjian** [comment]
Closing this issue as it will be addressed in the [Full Site Editing](https://github.com/godaddy-wordpress/go/pull/855) work currently underway in Go. You will be able to customize the header and footer template variations with blocks.
