### ISSUE TITLE
Extend Style Options in Customizer

### ISSUE THREAD

**Issue by vlaisavljevic** [godaddy-wordpress/go#754]
**Describe the feature:**
There is a suggestion for improving the Site Design option in the customizer, i.e adding additional options for text colours.
https://wordpress.org/support/topic/design-style-modern-color-bug/#post-15394883

**Comment by jrtashjian** [comment]
Closing this issue as we focus on the [Full Site Editing](https://github.com/godaddy-wordpress/go/pull/855) work currently underway in Go.

We will no longer be supporting the customizer as site editor replaces it.
