### ISSUE TITLE
Logo element is wrapped in an H1 tag

### ISSUE THREAD

**Issue by Hixsterino** [godaddy-wordpress/go#759]
The logo element is wrapped in an H1 tag. This results in 2 H1 tags on all pages. This is poor from a semantic and SEO perspective.

**Comment by EvanHerman** [comment]
@Hixsterino What version of Go do you have installed? And what design style are you using? I am not seeing two H1 elements on the page.

<img width="841" alt="image" src="https://user-images.githubusercontent.com/5321364/159703017-0f93f027-f69b-4eac-b19c-3093e59e3f87.png">

**Comment by Hixsterino** [comment]
Thanks @EvanHerman - I'm using Version: 1.5.3 with the Playful child theme.
Here's a link to the site in question -> https://oldschoolbmx.uk/

<img width="774" alt="Screenshot 2022-03-23 at 12 58 22" src="https://user-images.githubusercontent.com/102153596/159704725-c40f1133-f81b-4070-8253-6a5ec0118388.png">

**Comment by Hixsterino** [comment]
Hi @EvanHerman - any thoughts on this? can you reproduce?

**Comment by EvanHerman** [comment]
@Hixsterino Is your homepage set to a custom page? I'll give it another try and see if I can reproduce.

**Comment by jrtashjian** [comment]
Closing as resolved in #766.
