### ISSUE TITLE
Disable search on 404 page

### ISSUE THREAD

**Issue by mariuszostrowski** [godaddy-wordpress/go#776]
**Describe the bug:**
Please add an option to disable search form on 404 page

**Expected behavior:**

**Screenshot(s):**

**Priority** (select one):
- [ ] High - Functional blocker
- [ ] Medium - Doesn't work as expected 
- [*] Low - Not a big deal but we'd want to get to this eventually

**Comment by jrtashjian** [comment]
Closing this issue as it will be addressed in the [Full Site Editing](https://github.com/godaddy-wordpress/go/pull/855) work currently underway in Go.
