### ISSUE TITLE
Sub menu bug on mobile (Go Theme - Wordpress)

### ISSUE THREAD

**Issue by frc34** [godaddy-wordpress/go#785]
Hi,

I'm using the Go theme by GoDaddy on Wordpress and I'm really happy with it.
But I'm facing some issue with sub menus on mobile: the dropdown menu doesn't work properly on mobile, though it does on desktop.

Here's the issue:

Menu item 
   > sub item (appears but no dropdown for further "sub-sub" items when clicking on it)
      >> sub sub item (won't appear on mobile/can't be accessed)

E.g. with actual menu:

ABOUT (menu item = empty link #)
  > ONLINE (sub menu item = empty link # > nothing happens/nothing appears under it when clicking on it on mobile, although it works on desktop version)
     >> SCHEDULE (sub sub menu item = link to a page, won't appear on menu) 
     >> INFO (sub sub menu item = link to a page, won't appear on menu)

It's really bugging me as I can't rearrange the pages in my menu... What could be done to solve this?

Thanks for your help!

Best,

**Comment by jrtashjian** [comment]
Closing this issue as it will be addressed in the [Full Site Editing](https://github.com/godaddy-wordpress/go/pull/855) work currently underway in Go.
