### ISSUE TITLE
Broken align-wide theme support in 1.6.2

### ISSUE THREAD

**Issue by mserajnik** [godaddy-wordpress/go#798]
**Describe the bug:**

The 1.6.2 release apparently broke the `align-wide` theme support (it's working in 1.6.1); the button is no longer present on Gutenberg blocks that should support it (like CoBlocks rows).

I assume it's because of the introduction of the `theme.json` in [this commit](https://github.com/godaddy-wordpress/go/commit/b86ca1ed320af0ee88d1f4935a49b62a74a322a0) which overrules the `add_theme_support('align-wide')`.

**Expected behavior:**

`align-wide` theme support should work.

**Screenshot(s):**

**Priority** (select one):
- [ ] High - Functional blocker
- [x] Medium - Doesn't work as expected 
- [ ] Low - Not a big deal but we'd want to get to this eventually

**Comment by kinetifex** [comment]
I'm encountering an alignment issue that popped up from 1.6.1 to 1.6.2 which is possibly related. My column blocks are all left aligned on the page.

**Comment by davidpreta** [comment]
I'm having the same issues, not sure how to fix it.
