### ISSUE TITLE
Update cart.php for woocommerce

### ISSUE THREAD

**Issue by lglasgow-godaddy** [godaddy-wordpress/go#816]
**Describe the bug:**
When WooCommerce updates or does a status check it says that the `cart.php` file is out of date. The version in the theme is `3.8` the latest version is `7.0.1`.

**Expected behavior:**
According to WooCommerce the file should be `v7.0.1`

**Screenshot(s):**
I updated mine so I don't have the error message so don't have an screenshot for it.

**Priority** (select one):
- [ ] High - Functional blocker
- [ ] Medium - Doesn't work as expected 
- [x] Low - Not a big deal but we'd want to get to this eventually

**Comment by helgatheviking** [comment]
This needs to be re-opened... as cart.php is currently v7.4

**Comment by olafleur-godaddy** [comment]
Yeah, also mentioned here : https://wordpress.org/support/topic/go-woocommerce/
Reopening.
