### ISSUE TITLE
Issue when using Go and CoBlocks

### ISSUE THREAD

**Issue by gdaleks** [godaddy-wordpress/go#831]
When adding a masonry gallery block from CoBlocks while the Go theme is active, the gallery is aligned to the left: https://ibb.co/6Ht4P8f

When I use a different theme (e.g. Astra) the block is properly centered.

Originally reported in: https://wordpress.org/support/topic/how-to-center-home-page-content/#post-16293937

**Comment by jrtashjian** [comment]
Closing this issue as it will be addressed in the [Full Site Editing](https://github.com/godaddy-wordpress/go/pull/855) work currently underway in Go.
