### ISSUE TITLE
Feature req: back-to-top button

### ISSUE THREAD

**Issue by gdandrija** [godaddy-wordpress/go#844]
**Describe the bug:**
The user would like to create a back-to-top button. Originally submitted at WordPress.org:
https://wordpress.org/support/topic/feature-req-back-to-top-button/

"Hi guys,

would you consider adding an optional back-to-top feature in this theme just to avoid installing other plugins. If not, which lightweight plugin would you recommend?"

**Priority** (select one):
- [ ] High - Functional blocker
- [ ] Medium - Doesn't work as expected 
- [x] Low - Not a big deal but we'd want to get to this eventually

**Comment by jrtashjian** [comment]
Closing this issue as we focus on the [Full Site Editing](https://github.com/godaddy-wordpress/go/pull/855) work currently underway in Go.

This feature is more about site functionality rather than design and templates, where Go is focused.
