### ISSUE TITLE
Add Quora to Social Icons

### ISSUE THREAD

**Issue by PavleMarjanovic** [godaddy-wordpress/go#846]
**Describe the bug:**
Add Quora to Social Icons
**Expected behavior:**
Be able to add Quora within Social Icons
**Screenshot(s):**

**Priority** (select one):
- [ ] High - Functional blocker
- [ ] Medium - Doesn't work as expected 
- [X] Low - Not a big deal but we'd want to get to this eventually

**Comment by jrtashjian** [comment]
Closing this issue as it will be addressed in the [Full Site Editing](https://github.com/godaddy-wordpress/go/pull/855) work currently underway in Go.

We will be utilizing the core [Social Icons block](https://wordpress.org/documentation/article/social-icons/) in WordPress to output which can be extended to add new services. However, we won't be extending it in Go and although there are no current plans, it would make more sense in [CoBlocks](https://github.com/godaddy-wordpress/coblocks/). Alternatively, you can submit an issue/pr to [The Block Editor project](https://github.com/WordPress/gutenberg/) to push for the Quora service to be added.
