### ISSUE TITLE
FSE: Block settings in header.

### ISSUE THREAD

**Issue by AnthonyLedesma** [godaddy-wordpress/go#857]
Made this Gif showing the use of block settings in the header template part. Seems like some of the horizontal and vertical alignment options work for the row blocks but it also seems that several of the block states have block settings that do not make a difference in the editor. For example, text alignment options do not seem to work nor do block width options.  It would be really cool if we could restrict those block settings in cases like this where the settings do not persist anyway. Overall I don't see this as a major issue but it should be something we are aware of.

![HeaderBlockSettings](https://user-images.githubusercontent.com/30462574/230627816-39080907-8376-4d9b-b6f7-73dc3cc01045.gif)

**Comment by jrtashjian** [comment]
This isn't something we have control of nor could we accurately hide/show them. The controls do actually make changes we just don't see them visually because the container (in the case of text alignment) is not larger than the text it contains.
