### ISSUE TITLE
FSE: Search block in header?

### ISSUE THREAD

**Issue by AnthonyLedesma** [godaddy-wordpress/go#861]
Looks like all classic headers had a search option. We also had the option to hide the search option for users in the classic customizer. It does not like any of the new template headers use the search block.

**Classic customizer**
![Screen Shot 2023-04-07 at 10 42 00 AM](https://user-images.githubusercontent.com/30462574/230653572-c44c354d-760f-49d4-b798-3e1f87d334de.png)

**Comment by jrtashjian** [comment]
This is another piece we lose in the transition. I was going to use the `core/search` block in place of what we had but it doesn't accomplish the same thing. I think this would actually be a great addition to CoBlocks so I've [created a new issue there](https://github.com/godaddy-wordpress/coblocks/issues/2523).
