### ISSUE TITLE
Outdated WooCommerce Template Files

### ISSUE THREAD

**Issue by dsnow-godaddy** [godaddy-wordpress/go#872]
**Describe the bug:**
Getting the message "Your theme (Go) contains outdated copies of some WooCommerce template files."

From WooCommerce » Status
Your theme has a woocommerce.php file, you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.

go/woocommerce/cart/cart.php version 7.4.0 is out of date. The core version is 7.8.0

**Expected behavior:**
The WordPress Admin should not display this message in template files are updated.  The WooCommerce Status page would not display any template errors.

**Screenshot(s):**
https://cloud.skyver.ge/8LuYjD5q
https://cloud.skyver.ge/lluXDEoJ

**Priority** (select one):
- [ ] High - Functional blocker
- [ ] Medium - Doesn't work as expected 
- [X] Low - Not a big deal but we'd want to get to this eventually

**Comment by EvanHerman** [comment]
This has now been updated in the `1.8.2` release that we shipped last night. Thanks for reporting that 👍 
https://wordpress.org/themes/go/
